apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-stack
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/elastic/cloud-on-k8s.git
    targetRevision: main
    path: deploy/eck-stack
    helm:
      values: "values.yaml"
      releaseName: eck-stack
