apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-stack
  namespace: argocd
spec:
  destination:
    namespace: eck-stack
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: eck-stack
    targetRevision: 0.4.0
    helm:
      values: |
        eck-elasticsearch:
          enabled: true
          annotations:
            eck.k8s.elastic.co/license: basic
        eck-kibana:
          enabled: true
          annotations:
            eck.k8s.elastic.co/license: basic
        eck-agent:
          enabled: true
          annotations:
            eck.k8s.elastic.co/license: basic
        eck-fleet-server:
          annotations:
            eck.k8s.elastic.co/license: basic
          enabled: true
      releaseName: elastic-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
