apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prom-stack
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/prometheus-community/helm-charts'
    path: charts/kube-prometheus-stack
    targetRevision: HEAD
    helm:
      releaseName: prometheus-community
      values: |
        alertmanager:
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
            hosts:
              - alertmanager.example.com
          service:
            type: ClusterIP
          routePrefix: /alertmanager
        grafana:
          adminPassword: "admin"
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
            hosts:
              - grafana.example.com
          service:
            type: ClusterIP
          routePrefix: /grafana
        prometheus:
          alertmanagerURL: http://alertmanager:9093
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
            hosts:
              - prometheus.example.com
          service:
            type: ClusterIP
          routePrefix: /prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true